##control/execute vis_ev_e_v1.mac
# Macro file for the initialization phase of "TestEm5.cc"
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 2
/run/verbose 2
/run/setCut 10 um
#/lxphoton/phys/addPhysics  emstandard_opt0

#/lxphoton/det/GammaBeamDumpZ   1000.0  mm
#/lxphoton/det/GammaBeamDumpMaterial Copper

#/control/execute lxmagnet_hics.mac

#/lxphoton/det/GammaBeamDumpZ   1000.0  mm
#/lxphoton/det/GammaBeamDumpMaterial G4_W
#/lxphoton/det/DistanceBeamDumpBSM 1.5 m
#/lxphoton/det/GammaBeamDumpR 20 cm
#/lxphoton/det/GammaBeamDumpWrapMaterial G4_Pb
#/lxphoton/det/GammaBeamDumpWrapR 50 cm

#/lxphoton/det/GammaBeamDumpWrapMaterial G4_Pb
#/lxphoton/det/GammaBeamDumpWrapR        50.0 cm

#/lxphoton/det/GammaBeamDumpAirR          100.0 mm
#/lxphoton/det/GammaBeamDumpAirGapZ       20.0 cm
#/lxphoton/det/GammaBeamDumpMagnetGapZ    50.0 mm
#/lxphoton/det/GammaBeamDumpMagnetThick   100.0 mm
#/lxphoton/det/magnet_field/value GammaDump By 1.5 tesla

# Model of BSM detector, supported options: calice, generic (default).
#/lxphoton/det/model   BSMDetector   calice

/run/initialize

#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors

# Background color:
#/vis/viewer/set/background 0.8 0.8 0.8
#/vis/viewer/set/background 1.0 1.0 1.0
#/vis/viewer/set/background white
/vis/viewer/set/background 0.85 0.85 0.85

#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
#/vis/viewer/set/viewpointThetaPhi 90. 0.
#/vis/viewer/set/viewpointVector -1 0 0
#/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/set/viewpointVector -0.00001 0.99999 0
#/vis/viewer/set/viewpointVector -0.99999 0.00001 0

#
# Specify zoom value:
/vis/viewer/zoom 1.4
#
# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
#/vis/viewer/set/style surface

# To get nice view
#/vis/geometry/set/visibility World -1 true
#/vis/geometry/set/visibility World 0 false
#/vis/geometry/set/visibility Envelope 0 false
#/vis/viewer/set/style surface
#/vis/viewer/set/hiddenMarker true
#/vis/viewer/set/viewpointThetaPhi 210 150

# Draw geometry in surface mode with colors settings
/control/macroPath /home/sqy/work/luxe/g4sim/lxelgeo/mac
/control/execute vis_lx_color.mac
#/control/execute vis_grid.mac
#/control/execute vis_grid_xy.mac
#/control/execute vis_grid_yz.mac

#
# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 1 m
#/vis/scene/add/scale   # Simple scale line
#/vis/scene/add/scale 10 m z 0.9 0.9 0.9 manual 2.0 1.5 0 m
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
#/vis/scene/add/eventID # Drawn at end of event

#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set n yellow
/vis/modeling/trajectories/drawByParticleID-0/set p black

#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

#/control/execute hist_settings.mac

#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)

#/lxphoton/gun/beamType    mc
#/lxphoton/gun/MCParticlesFile   test_data_0.out
#/lxphoton/gun/MCParticlesFile   test_data1.out

#/lxphoton/gun/beamType    mono
#/lxphoton/gun/setPosZ   0.0 m
#/lxphoton/gun/setPosition  0.0  0.0  0.0 m

#/gun/particle e-
#/gun/particle gamma
#/gun/energy 16.5 GeV
#/gun/energy 5.0 GeV
#/gun/direction 0 0 1

#/run/beamOn 10

#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
